//
//  EmailMessage.swift
//  PerfectSMTPCore
//
//  See Documentation/swift6-nio-rewrite-plan.md §4.7.
//

import Foundation

/// Relative importance of a message. Mapped by `MIMEComposer` onto the
/// conventional (non-standardized, but universally recognized)
/// `X-Priority` / `Importance` header pair; `.normal` emits neither header.
public enum Priority: Sendable, Equatable {
    case high
    case normal
    case low
}

/// Fallback disposition for attachments/inline resources that don't set
/// their own `disposition`. Corresponds to Lasso 8.5's top-level
/// `-ContentDisposition` param — see plan §4.7's routing note.
public enum ContentDisposition: String, Sendable, Equatable {
    case attachment
    case inline
}

/// RFC 8058 one-click unsubscribe headers. `MIMEComposer` (Phase 5) emits
/// `List-Unsubscribe` from `mailto`/`url` (whichever are present, each
/// wrapped in angle brackets, comma-separated if both), and
/// `List-Unsubscribe-Post: List-Unsubscribe=One-Click` when `postOneClick`
/// is set — see `MIMEComposer.listUnsubscribeHeaders()`'s doc comment for
/// the exact emission rules (including why `postOneClick` requires `url`).
///
/// `mailto` is the bare mailbox (e.g. `"unsub@example.com"`, *not*
/// `"mailto:unsub@example.com"` — the composer supplies the `mailto:`
/// scheme itself) so the same value is also usable anywhere else a plain
/// address is expected; a caller-supplied `mailto:` prefix is tolerated
/// (stripped, not doubled — see `MIMEComposer.listUnsubscribeHeaders()`'s
/// doc comment). `url` is the full one-click target, scheme included, and
/// **must be `https://`** — RFC 8058 §3.1: "The List-Unsubscribe header
/// field MUST contain one HTTPS URI." `MIMEComposer` enforces this
/// unconditionally (whenever `url` is set, not only when `postOneClick` is
/// true) and throws `ComposerError.listUnsubscribeURLMustBeHTTPS` rather
/// than silently accepting or downgrading a non-HTTPS value.
public struct ListUnsubscribe: Sendable, Hashable {
    public var mailto: String?
    public var url: String?
    /// When true, also emit `List-Unsubscribe-Post: List-Unsubscribe=One-Click`
    /// (RFC 8058 §2) — the "one-click" mechanism Gmail/Yahoo require for
    /// bulk senders. Applies only to the `url` (HTTPS POST) mechanism, not
    /// `mailto`; composition throws if this is `true` but `url` is nil,
    /// since there is then no one-click target for the header to describe
    /// (a caller configuration error, not something to silently degrade).
    public var postOneClick: Bool

    public init(mailto: String? = nil, url: String? = nil, postOneClick: Bool = false) {
        self.mailto = mailto
        self.url = url
        self.postOneClick = postOneClick
    }
}

/// Informal, de facto header (not itself specified by RFC 3834, but
/// conventionally paired with it — sendmail/qmail lineage, RFC 2076 §3.5's
/// informational survey of widely-deployed, non-standard headers) used by
/// mailing-list software and many receivers for automated-mail loop
/// suppression (e.g. "don't send an out-of-office auto-reply to this").
/// `bulk`/`list`/`junk` is the conventional minimal set actually seen in
/// the wild. `MIMEComposer` (Phase 5) emits `Precedence: <rawValue>` when
/// set.
public enum Precedence: String, Sendable, Equatable {
    case bulk
    case list
    case junk
}

/// Automated-response signaling. `MIMEComposer` (Phase 5) emits
/// `Auto-Submitted: <rawValue>` when set. Per the milestone review's direct
/// fetch of RFC 3834's own ABNF: only `auto-generated` and `auto-replied`
/// are RFC 3834 §5-native keywords. `auto-notified` is a valid, correctly
/// spelled value, but it is registered via RFC 5436 (the IANA "Auto-
/// Submitted Header Field Keywords" registry that RFC 3834 §5 itself
/// defers to for keywords beyond its own two), not defined by RFC 3834
/// directly.
public enum AutoSubmitted: String, Sendable, Equatable {
    /// RFC 3834 §5-native.
    case autoGenerated = "auto-generated"
    /// RFC 3834 §5-native.
    case autoReplied = "auto-replied"
    /// IANA-registered via RFC 5436, not RFC 3834 itself.
    case autoNotified = "auto-notified"
}

/// An inline, `cid:`-referenced resource for `multipart/related` (Lasso
/// `-htmlImages`). Payload is a value type (`Data`), never a stream/file
/// handle — required for `Sendable` per the plan's §4.7 caveat.
public struct InlineResource: Sendable {
    /// The `Content-ID`, without angle brackets. Referenced from HTML body
    /// as `cid:<contentID>`.
    public var contentID: String
    public var filename: String?
    public var contentType: String
    public var data: Data

    public init(contentID: String, filename: String? = nil, contentType: String, data: Data) {
        self.contentID = contentID
        self.filename = filename
        self.contentType = contentType
        self.data = data
    }
}

/// A `multipart/mixed` attachment. Payload is a value type (`Data`), never
/// a stream/file handle — same Sendability constraint as `InlineResource`.
public struct Attachment: Sendable {
    public var filename: String
    public var contentType: String
    public var data: Data
    /// Overrides `EmailMessage.defaultDisposition` for this attachment only.
    public var disposition: ContentDisposition?

    public init(filename: String, contentType: String, data: Data, disposition: ContentDisposition? = nil) {
        self.filename = filename
        self.contentType = contentType
        self.data = data
        self.disposition = disposition
    }
}

/// A composed email message — headers and body content, but deliberately
/// no envelope/routing information. This is the corrected Bug #1 fix
/// (plan §4.7): there is no `bcc` field anywhere on this type. Bcc
/// addresses only ever exist as extra entries in `SMTPEnvelope.recipients`,
/// supplied by the caller-facing `bcc:` parameter on `SMTPMailer.send`
/// (Phase 1) — never as part of the message that gets serialized and sent
/// to every recipient.
public struct EmailMessage: Sendable {
    public var from: EmailAddress
    /// Distinct `Sender:` header (Lasso `-sender`) — used when the message
    /// is sent on behalf of `from` by a different actual sender.
    public var sender: EmailAddress?
    public var replyTo: [EmailAddress]
    public var to: [EmailAddress]
    public var cc: [EmailAddress]
    // NOTE: no `bcc` field here at all — see the corrected Bcc fix above.
    public var subject: String
    public var textBody: String?
    public var htmlBody: String?
    public var inlineImages: [InlineResource]
    public var attachments: [Attachment]
    public var priority: Priority
    /// Auto-synthesized by `MIMEComposer` when nil — see §7's "no
    /// guaranteed Date synthesis" gap.
    public var date: Date?
    /// Auto-synthesized by `MIMEComposer` when nil, domain-scoped per
    /// `MIMEComposer`'s `messageIDDomain` — see its doc comment for the
    /// Phase 0 scoping decision (DKIM `d=`/envelope-from isn't wired up
    /// until Phase 1/2).
    public var messageID: String?
    public var inReplyTo: String?
    public var references: [String]
    public var listUnsubscribe: ListUnsubscribe?
    public var autoSubmitted: AutoSubmitted?
    /// De facto loop-suppression header, conventionally paired with
    /// `autoSubmitted` — see `Precedence`'s doc comment. Not itself
    /// specified by RFC 3834; kept as a distinct field from
    /// `autoSubmitted` since a caller may reasonably want one without the
    /// other.
    public var precedence: Precedence?
    /// Caller-supplied extra headers, run through `MIMEComposer`'s denylist
    /// at composition time — see its `forbiddenExtraHeaderNames`. This is
    /// the reintroduction vector the Bug #1 fix specifically closes: a
    /// caller cannot smuggle a `Bcc:`/`To:`/etc. header back in here.
    public var extraHeaders: [(name: String, value: String)]
    public var charset: String
    public var defaultDisposition: ContentDisposition

    /// Only `from` is required -- everything else defaults to "absent" (an
    /// empty recipient list, no body) and is intended to be set afterward
    /// via `var message = EmailMessage(from: ...); message.to = [...]`,
    /// matching the pattern this library's own tests and the user guide's
    /// examples use throughout, rather than a single large initializer
    /// call. `MIMEComposer.compose()` (not this initializer) is what
    /// actually validates the result -- e.g. it throws if both `textBody`
    /// and `htmlBody` are nil, since a message needs at least one -- so
    /// constructing an otherwise-incomplete `EmailMessage` here is not
    /// itself an error.
    ///
    /// - Parameters:
    ///   - from: The `From:` header. Always required; there is no default
    ///     recipient-less sender identity.
    ///   - sender: A distinct `Sender:` header (RFC 5322 §3.6.2) --
    ///     set this only when the message is being sent on `from`'s behalf
    ///     by a different actual sender (e.g. an assistant sending for a
    ///     manager). Leave `nil` for the ordinary case where `from` and the
    ///     actual sender are the same mailbox.
    ///   - to/cc: Recipients that appear in the corresponding headers *and*
    ///     become part of the SMTP envelope's `RCPT TO` list when this
    ///     message is passed to `SMTPMailer.send`. There is deliberately no
    ///     `bcc` parameter here -- Bcc addresses are supplied separately,
    ///     as extra envelope recipients that never appear in any header
    ///     sent to any recipient. See `SMTPMailer.send(_:bcc:envelopeFrom:)`.
    ///   - date/messageID: Leave `nil` to have `MIMEComposer` auto-
    ///     synthesize both at composition time (a real wall-clock `Date:`
    ///     header, and a `Message-ID` scoped to the sending domain) --
    ///     most callers should leave these unset rather than generating
    ///     their own.
    ///   - extraHeaders: Caller-supplied additional headers, checked at
    ///     composition time against `MIMEComposer.forbiddenExtraHeaderNames`
    ///     (`Bcc`, `To`, `From`, `Message-ID`, `DKIM-Signature`, and other
    ///     headers this library already manages) -- an attempt to smuggle
    ///     one of those back in here throws `ComposerError.forbiddenHeader`
    ///     rather than being silently overwritten or accepted.
    ///   - defaultDisposition: Applied to every `Attachment` that doesn't
    ///     set its own `disposition`; has no effect on `inlineImages`,
    ///     which are always `Content-Disposition: inline` by construction.
    public init(
        from: EmailAddress,
        sender: EmailAddress? = nil,
        replyTo: [EmailAddress] = [],
        to: [EmailAddress] = [],
        cc: [EmailAddress] = [],
        subject: String = "",
        textBody: String? = nil,
        htmlBody: String? = nil,
        inlineImages: [InlineResource] = [],
        attachments: [Attachment] = [],
        priority: Priority = .normal,
        date: Date? = nil,
        messageID: String? = nil,
        inReplyTo: String? = nil,
        references: [String] = [],
        listUnsubscribe: ListUnsubscribe? = nil,
        autoSubmitted: AutoSubmitted? = nil,
        precedence: Precedence? = nil,
        extraHeaders: [(name: String, value: String)] = [],
        charset: String = "utf-8",
        defaultDisposition: ContentDisposition = .attachment
    ) {
        self.from = from
        self.sender = sender
        self.replyTo = replyTo
        self.to = to
        self.cc = cc
        self.subject = subject
        self.textBody = textBody
        self.htmlBody = htmlBody
        self.inlineImages = inlineImages
        self.attachments = attachments
        self.priority = priority
        self.date = date
        self.messageID = messageID
        self.inReplyTo = inReplyTo
        self.references = references
        self.listUnsubscribe = listUnsubscribe
        self.autoSubmitted = autoSubmitted
        self.precedence = precedence
        self.extraHeaders = extraHeaders
        self.charset = charset
        self.defaultDisposition = defaultDisposition
    }
}
