//
//  EmailMessage.swift
//  PerfectSMTPCore
//
//  See Documentation/swift6-nio-rewrite-plan.md §4.7.
//

import Foundation

/// Relative importance of a message. Mapped by `MIMEComposer` onto the
/// conventional (non-standardized, but universally recognized)
/// `X-Priority` / `Importance` header pair; `.normal` emits neither header.
public enum Priority: Sendable, Equatable {
    case high
    case normal
    case low
}

/// Fallback disposition for attachments/inline resources that don't set
/// their own `disposition`. Corresponds to Lasso 8.5's top-level
/// `-ContentDisposition` param — see plan §4.7's routing note.
public enum ContentDisposition: String, Sendable, Equatable {
    case attachment
    case inline
}

/// RFC 8058 one-click unsubscribe headers. `MIMEComposer` (Phase 5) emits
/// `List-Unsubscribe` from `mailto`/`url` (whichever are present, each
/// wrapped in angle brackets, comma-separated if both), and
/// `List-Unsubscribe-Post: List-Unsubscribe=One-Click` when `postOneClick`
/// is set — see `MIMEComposer.listUnsubscribeHeaders()`'s doc comment for
/// the exact emission rules (including why `postOneClick` requires `url`).
///
/// `mailto` is the bare mailbox (e.g. `"unsub@example.com"`, *not*
/// `"mailto:unsub@example.com"` — the composer supplies the `mailto:`
/// scheme itself) so the same value is also usable anywhere else a plain
/// address is expected; a caller-supplied `mailto:` prefix is tolerated
/// (stripped, not doubled — see `MIMEComposer.listUnsubscribeHeaders()`'s
/// doc comment). `url` is the full one-click target, scheme included, and
/// **must be `https://`** — RFC 8058 §3.1: "The List-Unsubscribe header
/// field MUST contain one HTTPS URI." `MIMEComposer` enforces this
/// unconditionally (whenever `url` is set, not only when `postOneClick` is
/// true) and throws `ComposerError.listUnsubscribeURLMustBeHTTPS` rather
/// than silently accepting or downgrading a non-HTTPS value.
public struct ListUnsubscribe: Sendable, Hashable {
    public var mailto: String?
    public var url: String?
    /// When true, also emit `List-Unsubscribe-Post: List-Unsubscribe=One-Click`
    /// (RFC 8058 §2) — the "one-click" mechanism Gmail/Yahoo require for
    /// bulk senders. Applies only to the `url` (HTTPS POST) mechanism, not
    /// `mailto`; composition throws if this is `true` but `url` is nil,
    /// since there is then no one-click target for the header to describe
    /// (a caller configuration error, not something to silently degrade).
    public var postOneClick: Bool

    public init(mailto: String? = nil, url: String? = nil, postOneClick: Bool = false) {
        self.mailto = mailto
        self.url = url
        self.postOneClick = postOneClick
    }
}

/// Informal, de facto header (not itself specified by RFC 3834, but
/// conventionally paired with it — sendmail/qmail lineage, RFC 2076 §3.5's
/// informational survey of widely-deployed, non-standard headers) used by
/// mailing-list software and many receivers for automated-mail loop
/// suppression (e.g. "don't send an out-of-office auto-reply to this").
/// `bulk`/`list`/`junk` is the conventional minimal set actually seen in
/// the wild. `MIMEComposer` (Phase 5) emits `Precedence: <rawValue>` when
/// set.
public enum Precedence: String, Sendable, Equatable {
    case bulk
    case list
    case junk
}

/// Automated-response signaling. `MIMEComposer` (Phase 5) emits
/// `Auto-Submitted: <rawValue>` when set. Per the milestone review's direct
/// fetch of RFC 3834's own ABNF: only `auto-generated` and `auto-replied`
/// are RFC 3834 §5-native keywords. `auto-notified` is a valid, correctly
/// spelled value, but it is registered via RFC 5436 (the IANA "Auto-
/// Submitted Header Field Keywords" registry that RFC 3834 §5 itself
/// defers to for keywords beyond its own two), not defined by RFC 3834
/// directly.
public enum AutoSubmitted: String, Sendable, Equatable {
    /// RFC 3834 §5-native.
    case autoGenerated = "auto-generated"
    /// RFC 3834 §5-native.
    case autoReplied = "auto-replied"
    /// IANA-registered via RFC 5436, not RFC 3834 itself.
    case autoNotified = "auto-notified"
}

/// Caller-supplied override for the auto-computed `Content-Transfer-Encoding`
/// of the message's primary body (see `EmailMessage.bodyTransferEncodingOverride`'s
/// doc comment for what "primary body" means and when this override
/// applies). Explicitly typed rather than a raw string, so `MIMEComposer`
/// can validate it against the actual body bytes at compose time instead of
/// trusting an arbitrary caller-supplied label.
///
/// RFC 2045 §6.1 also defines `8bit` and `binary` mechanisms, but neither is
/// offered here:
/// - `8bit`/`binary` are identity (no-transform) labels, not real encodings
///   (RFC 2045 §6.2: "The Content-Transfer-Encoding values '7bit', '8bit',
///   and 'binary' all mean that the identity (i.e. NO) encoding
///   transformation has been performed"). Offering them as an "override"
///   alongside two encodings that actually transform the bytes into the
///   7bit range would invite exactly the mislabeling risk this feature
///   exists to prevent, for no benefit — a caller who wants an
///   unencoded/binary-domain body can already get validated 7bit-safety via
///   `.sevenBit`, or a real transform via `.quotedPrintable`/`.base64`.
/// - Concretely, in this codebase: `Capabilities.swift` parses the `8BITMIME`
///   EHLO capability into `eightBitMIME`, but nothing in the transport layer
///   ever reads that flag to negotiate `MAIL FROM ... BODY=8BITMIME` (RFC
///   6152) before actually sending unencoded 8-bit body octets. Emitting a
///   part labeled `8bit` today would misdescribe what was actually
///   negotiated with the server — the same class of transit-corruption risk
///   labeling non-ASCII content `7bit` would create, just via a different
///   mechanism (relays/gateways enforcing 7bit-clean transport on a
///   connection that never advertised/requested 8BITMIME, rather than
///   silently stripping the 8th bit).
/// - `binary` is even further out of scope: RFC 2045 §6.2 says outright
///   "there are no standardized Internet mail transports for which it is
///   legitimate to include unencoded binary data in mail bodies," and RFC
///   2045 §6.4 forbids any non-`7bit`/`8bit`/`binary` encoding on composite
///   (multipart) entities regardless — this library has no `BINARYMIME`
///   (RFC 3030) support at all.
public enum ContentTransferEncodingOverride: Sendable, Equatable {
    /// Claims the body is already 7bit-clean ASCII with no transformation
    /// applied. `MIMEComposer` validates this against the actual body bytes
    /// at compose time and throws rather than emitting a mislabeled `7bit`
    /// part — RFC 2045 §6.2: "Labelling unencoded data containing 8bit
    /// characters as '7bit' is not allowed."
    case sevenBit
    /// Applies RFC 2045 §6.7 quoted-printable encoding to the body,
    /// regardless of what `MIMEComposer` would otherwise have chosen. Always
    /// representable, so no content-based validation is needed.
    case quotedPrintable
    /// Applies RFC 2045 §6.8 base64 encoding to the body, regardless of what
    /// `MIMEComposer` would otherwise have chosen. Always representable, so
    /// no content-based validation is needed.
    case base64
}

/// An inline, `cid:`-referenced resource for `multipart/related` (Lasso
/// `-htmlImages`). Payload is a value type (`Data`), never a stream/file
/// handle — required for `Sendable` per the plan's §4.7 caveat.
public struct InlineResource: Sendable {
    /// The `Content-ID`, without angle brackets. Referenced from HTML body
    /// as `cid:<contentID>`.
    public var contentID: String
    public var filename: String?
    public var contentType: String
    public var data: Data

    public init(contentID: String, filename: String? = nil, contentType: String, data: Data) {
        self.contentID = contentID
        self.filename = filename
        self.contentType = contentType
        self.data = data
    }
}

/// A `multipart/mixed` attachment. Payload is a value type (`Data`), never
/// a stream/file handle — same Sendability constraint as `InlineResource`.
public struct Attachment: Sendable {
    public var filename: String
    public var contentType: String
    public var data: Data
    /// Overrides `EmailMessage.defaultDisposition` for this attachment only.
    public var disposition: ContentDisposition?

    public init(filename: String, contentType: String, data: Data, disposition: ContentDisposition? = nil) {
        self.filename = filename
        self.contentType = contentType
        self.data = data
        self.disposition = disposition
    }
}

/// A composed email message — headers and body content, but deliberately
/// no envelope/routing information. This is the corrected Bug #1 fix
/// (plan §4.7): there is no `bcc` field anywhere on this type. Bcc
/// addresses only ever exist as extra entries in `SMTPEnvelope.recipients`,
/// supplied by the caller-facing `bcc:` parameter on `SMTPMailer.send`
/// (Phase 1) — never as part of the message that gets serialized and sent
/// to every recipient.
public struct EmailMessage: Sendable {
    public var from: EmailAddress
    /// Distinct `Sender:` header (Lasso `-sender`) — used when the message
    /// is sent on behalf of `from` by a different actual sender.
    public var sender: EmailAddress?
    public var replyTo: [EmailAddress]
    public var to: [EmailAddress]
    public var cc: [EmailAddress]
    // NOTE: no `bcc` field here at all — see the corrected Bcc fix above.
    public var subject: String
    public var textBody: String?
    public var htmlBody: String?
    /// Overrides the declared `Content-Type` of the message's primary body
    /// part instead of the value `MIMEComposer` would otherwise compute
    /// (`text/plain; charset=...` or `text/html; charset=...`). Rare,
    /// legacy-compatibility escape hatch for the Lasso `-contentType`
    /// dash-param — most callers should leave this `nil` and let
    /// `MIMEComposer` choose correctly.
    ///
    /// **Applies only when exactly one of `textBody`/`htmlBody` is set.**
    /// When both are set, the message composes to a `multipart/alternative`
    /// wrapper containing two leaf parts (plain and html) — there is no
    /// single "the body" for a single-target override to unambiguously mean,
    /// and the legacy Lasso tag this exists for is a simple, single-body
    /// send (Lasso 8.5's original mail-send tags took one body plus one
    /// content-type/encoding pair, not a per-alternative override). Setting
    /// this alongside both `textBody` and `htmlBody` therefore throws
    /// `MIMEComposer.ComposerError.bodyOverrideRequiresSingleBodyPart` at
    /// compose time rather than guessing which alternative (or the wrapper
    /// itself) the caller meant.
    ///
    /// Emitted verbatim (not validated as a well-formed MIME type), but
    /// still routed through the same CRLF-injection rejection
    /// (`HeaderEncoder.rejectHeaderInjection`) every other caller-controlled
    /// header value in `MIMEComposer` goes through — a CRLF here throws
    /// `ComposerError.invalidHeaderValue("bodyContentTypeOverride")` rather
    /// than being silently stripped.
    public var bodyContentTypeOverride: String?
    /// Overrides the automatically-computed `Content-Transfer-Encoding` for
    /// the message's primary body part — same single-body-only applicability
    /// as `bodyContentTypeOverride` (see its doc comment; both fields share
    /// the same "which part does this apply to" answer and the same
    /// `bodyOverrideRequiresSingleBodyPart` failure mode when both `textBody`
    /// and `htmlBody` are set). Legacy-compatibility escape hatch for the
    /// Lasso `-transferEncoding` dash-param.
    ///
    /// `MIMEComposer` validates this against the actual body bytes at
    /// compose time and throws rather than silently emitting a mislabeled
    /// encoding that could corrupt the message in transit — see
    /// `ContentTransferEncodingOverride`'s doc comment for the full
    /// validation rules and RFC 2045 citations, and
    /// `ComposerError.sevenBitOverrideRequiresASCIIBody` for the specific
    /// failure this guards against.
    public var bodyTransferEncodingOverride: ContentTransferEncodingOverride?
    public var inlineImages: [InlineResource]
    public var attachments: [Attachment]
    public var priority: Priority
    /// Auto-synthesized by `MIMEComposer` when nil — see §7's "no
    /// guaranteed Date synthesis" gap.
    public var date: Date?
    /// Auto-synthesized by `MIMEComposer` when nil, domain-scoped per
    /// `MIMEComposer`'s `messageIDDomain` — see its doc comment for the
    /// Phase 0 scoping decision (DKIM `d=`/envelope-from isn't wired up
    /// until Phase 1/2).
    public var messageID: String?
    public var inReplyTo: String?
    public var references: [String]
    public var listUnsubscribe: ListUnsubscribe?
    public var autoSubmitted: AutoSubmitted?
    /// De facto loop-suppression header, conventionally paired with
    /// `autoSubmitted` — see `Precedence`'s doc comment. Not itself
    /// specified by RFC 3834; kept as a distinct field from
    /// `autoSubmitted` since a caller may reasonably want one without the
    /// other.
    public var precedence: Precedence?
    /// Caller-supplied extra headers, run through `MIMEComposer`'s denylist
    /// at composition time — see its `forbiddenExtraHeaderNames`. This is
    /// the reintroduction vector the Bug #1 fix specifically closes: a
    /// caller cannot smuggle a `Bcc:`/`To:`/etc. header back in here.
    public var extraHeaders: [(name: String, value: String)]
    public var charset: String
    public var defaultDisposition: ContentDisposition

    /// Only `from` is required -- everything else defaults to "absent" (an
    /// empty recipient list, no body) and is intended to be set afterward
    /// via `var message = EmailMessage(from: ...); message.to = [...]`,
    /// matching the pattern this library's own tests and the user guide's
    /// examples use throughout, rather than a single large initializer
    /// call. `MIMEComposer.compose()` (not this initializer) is what
    /// actually validates the result -- e.g. it throws if both `textBody`
    /// and `htmlBody` are nil, since a message needs at least one -- so
    /// constructing an otherwise-incomplete `EmailMessage` here is not
    /// itself an error.
    ///
    /// - Parameters:
    ///   - from: The `From:` header. Always required; there is no default
    ///     recipient-less sender identity.
    ///   - sender: A distinct `Sender:` header (RFC 5322 §3.6.2) --
    ///     set this only when the message is being sent on `from`'s behalf
    ///     by a different actual sender (e.g. an assistant sending for a
    ///     manager). Leave `nil` for the ordinary case where `from` and the
    ///     actual sender are the same mailbox.
    ///   - to/cc: Recipients that appear in the corresponding headers *and*
    ///     become part of the SMTP envelope's `RCPT TO` list when this
    ///     message is passed to `SMTPMailer.send`. There is deliberately no
    ///     `bcc` parameter here -- Bcc addresses are supplied separately,
    ///     as extra envelope recipients that never appear in any header
    ///     sent to any recipient. See `SMTPMailer.send(_:bcc:envelopeFrom:)`.
    ///   - date/messageID: Leave `nil` to have `MIMEComposer` auto-
    ///     synthesize both at composition time (a real wall-clock `Date:`
    ///     header, and a `Message-ID` scoped to the sending domain) --
    ///     most callers should leave these unset rather than generating
    ///     their own.
    ///   - extraHeaders: Caller-supplied additional headers, checked at
    ///     composition time against `MIMEComposer.forbiddenExtraHeaderNames`
    ///     (`Bcc`, `To`, `From`, `Message-ID`, `DKIM-Signature`, and other
    ///     headers this library already manages) -- an attempt to smuggle
    ///     one of those back in here throws `ComposerError.forbiddenHeader`
    ///     rather than being silently overwritten or accepted.
    ///   - defaultDisposition: Applied to every `Attachment` that doesn't
    ///     set its own `disposition`; has no effect on `inlineImages`,
    ///     which are always `Content-Disposition: inline` by construction.
    public init(
        from: EmailAddress,
        sender: EmailAddress? = nil,
        replyTo: [EmailAddress] = [],
        to: [EmailAddress] = [],
        cc: [EmailAddress] = [],
        subject: String = "",
        textBody: String? = nil,
        htmlBody: String? = nil,
        bodyContentTypeOverride: String? = nil,
        bodyTransferEncodingOverride: ContentTransferEncodingOverride? = nil,
        inlineImages: [InlineResource] = [],
        attachments: [Attachment] = [],
        priority: Priority = .normal,
        date: Date? = nil,
        messageID: String? = nil,
        inReplyTo: String? = nil,
        references: [String] = [],
        listUnsubscribe: ListUnsubscribe? = nil,
        autoSubmitted: AutoSubmitted? = nil,
        precedence: Precedence? = nil,
        extraHeaders: [(name: String, value: String)] = [],
        charset: String = "utf-8",
        defaultDisposition: ContentDisposition = .attachment
    ) {
        self.from = from
        self.sender = sender
        self.replyTo = replyTo
        self.to = to
        self.cc = cc
        self.subject = subject
        self.textBody = textBody
        self.htmlBody = htmlBody
        self.bodyContentTypeOverride = bodyContentTypeOverride
        self.bodyTransferEncodingOverride = bodyTransferEncodingOverride
        self.inlineImages = inlineImages
        self.attachments = attachments
        self.priority = priority
        self.date = date
        self.messageID = messageID
        self.inReplyTo = inReplyTo
        self.references = references
        self.listUnsubscribe = listUnsubscribe
        self.autoSubmitted = autoSubmitted
        self.precedence = precedence
        self.extraHeaders = extraHeaders
        self.charset = charset
        self.defaultDisposition = defaultDisposition
    }
}
